"""add audio_data to audio_events

Revision ID: cd0de5acf638
Revises: 4f1c57c0fe38
Create Date: 2026-05-09 09:30:17.607319
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cd0de5acf638'
down_revision: Union[str, None] = '4f1c57c0fe38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_versions_agent'), table_name='config_versions')
    op.drop_index(op.f('ix_config_versions_hash'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_handoff_history_agent'), table_name='handoff_history')
    op.drop_index(op.f('ix_handoff_history_status'), table_name='handoff_history')
    op.drop_index(op.f('ix_handoff_history_time'), table_name='handoff_history')
    op.drop_table('handoff_history')
    op.alter_column('agent_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_history', 'server_received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'agent_history', 'agents', ['agent_id'], ['agent_id'], ondelete='CASCADE')
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('audio_events', sa.Column('audio_data', sa.Text(), nullable=True))
    op.alter_column('audio_events', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('audio_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audio_transcriptions', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commands', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('commands', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('commands', 'requires_ack',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('commands', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('commands', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('commands', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('masters', 'max_agents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('masters', 'current_agent_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('masters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ONLINE'::character varying"))
    op.alter_column('masters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mesh_routes', 'hop_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('mesh_routes', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mesh_routes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_mesh_routes_source'), table_name='mesh_routes')
    op.drop_index(op.f('ix_mesh_routes_target'), table_name='mesh_routes')
    op.create_index(op.f('ix_mesh_routes_source_node'), 'mesh_routes', ['source_node'], unique=False)
    op.create_index(op.f('ix_mesh_routes_target_node'), 'mesh_routes', ['target_node'], unique=False)
    op.add_column('video_events', sa.Column('video_data', sa.Text(), nullable=True))
    op.alter_column('video_events', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('video_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_events', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('video_events', 'video_data')
    op.drop_index(op.f('ix_mesh_routes_target_node'), table_name='mesh_routes')
    op.drop_index(op.f('ix_mesh_routes_source_node'), table_name='mesh_routes')
    op.create_index(op.f('ix_mesh_routes_target'), 'mesh_routes', ['target_node'], unique=False)
    op.create_index(op.f('ix_mesh_routes_source'), 'mesh_routes', ['source_node'], unique=False)
    op.alter_column('mesh_routes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('mesh_routes', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mesh_routes', 'hop_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('masters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('masters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ONLINE'::character varying"))
    op.alter_column('masters', 'current_agent_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('masters', 'max_agents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('commands', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commands', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('commands', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('commands', 'requires_ack',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('commands', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('commands', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('audio_transcriptions', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audio_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audio_events', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('audio_events', 'audio_data')
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'agent_history', type_='foreignkey')
    op.alter_column('agent_history', 'server_received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('handoff_history',
    sa.Column('handoff_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('from_master_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('to_master_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('current_signal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_signal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offers_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('handoff_id', name=op.f('handoff_history_pkey'))
    )
    op.create_index(op.f('ix_handoff_history_time'), 'handoff_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_handoff_history_status'), 'handoff_history', ['status'], unique=False)
    op.create_index(op.f('ix_handoff_history_agent'), 'handoff_history', ['agent_id'], unique=False)
    op.create_table('config_versions',
    sa.Column('version_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('config_hash', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=20), server_default=sa.text("'FULL_REPLACE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('changed_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('previous_version_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rolled_back', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version_id', name=op.f('config_versions_pkey'))
    )
    op.create_index(op.f('ix_config_versions_hash'), 'config_versions', ['config_hash'], unique=False)
    op.create_index(op.f('ix_config_versions_agent'), 'config_versions', ['agent_id'], unique=False)
    # ### end Alembic commands ###
